### ISSUE TITLE
Fails to download "Systems Programming in Unix/Linux"

### ISSUE THREAD

**Issue by tzs** [tempname1024/springer-dl#2]
Because this script uses the book title as the directory name, and also uses the book title as part of the file name, it does not work on MacOS with books that have a "/" in their title. I'd expect that it also fails on other Unix systems and Linux.

**Comment by tempname1024** [comment]
Thanks for reporting this, the folder and filenames should absolutely be made filesystem-safe. This is fixed in 0122010.
